/** Mock /simulate now replays REAL-engine golden fixtures (#8). These tests
 * pin the lookup/interpolation contract and the fixture freshness guard — they
 * no longer assert shadow-engine dynamics (there is no shadow engine). */

import { describe, expect, it } from 'vitest'
import type { ScenarioParams, SimResult } from '../types'
import { ENGINE_VERSION } from '@/lib/engineVersion'
import { fixtures, runMockSim } from './sim'

const baseline = () => runMockSim({})

/** A well-formed SimResult with all series aligned to the age axis. */
function expectShape(r: SimResult) {
  const n = r.ages.length
  expect(n).toBeGreaterThan(1)
  for (const s of Object.values(r.deterministic)) expect(s.length).toBe(n)
  for (const s of Object.values(r.percentiles)) expect(s.length).toBe(n)
  expect(r.success_probability).toBeGreaterThanOrEqual(0)
  expect(r.success_probability).toBeLessThanOrEqual(1)
  for (let i = 0; i < n; i++) {
    expect(r.percentiles.p10[i]!).toBeLessThanOrEqual(r.percentiles.p50[i]!)
    expect(r.percentiles.p50[i]!).toBeLessThanOrEqual(r.percentiles.p90[i]!)
  }
  expect(Array.isArray(r.milestones)).toBe(true)
}

describe('fixture freshness guard', () => {
  it('fixtures were generated by the engine the app is built against', () => {
    expect(fixtures.engine_version).toBe(ENGINE_VERSION)
    expect(fixtures.baseline.result.engine_version).toBe(ENGINE_VERSION)
    expect(fixtures.seed).toBe(42)
    expect(fixtures.n_paths).toBe(1000)
  })
})

describe('runMockSim — golden fixture replay', () => {
  it('returns the baseline goldens for empty params', () => {
    const r = baseline()
    expectShape(r)
    expect(r.start_year).toBe(fixtures.reference_year)
    expect(r.ages[0]).toBe(fixtures.reference_year - 1980) // Brian, born 1980
  })

  it('is deterministic for a given param set', () => {
    expect(runMockSim({ spending_delta_pct: -10 })).toEqual(runMockSim({ spending_delta_pct: -10 }))
  })

  it('exact-matches a stored lattice point verbatim', () => {
    const stored = fixtures.axes
      .find((a) => a.id === 'spending_delta_pct')!
      .points.find((p) => p.value === -10)!.result
    expect(runMockSim({ spending_delta_pct: -10 })).toEqual(stored)
  })

  it('exact-matches a named scenario verbatim', () => {
    const coast = fixtures.scenarios.find((s) => s.name === 'Coast mode')!
    expect(runMockSim(coast.params)).toEqual(coast.result)
  })

  it('prunes no-op params back to the baseline goldens', () => {
    expect(runMockSim({ spending_delta_pct: 0, monthly_savings_delta: 0 })).toEqual(baseline())
    // annual_retirement_spending at the profile default is a no-op too
    expect(runMockSim({ annual_retirement_spending: 80000 })).toEqual(baseline())
  })
})

describe('directional properties (now sourced from the real engine)', () => {
  it('saving more raises the median ending net worth', () => {
    const lo = runMockSim({ monthly_savings_delta: -3000 })
    const hi = runMockSim({ monthly_savings_delta: 3000 })
    expect(hi.ending_net_worth.p50).toBeGreaterThan(lo.ending_net_worth.p50)
  })

  it('retiring later raises success probability', () => {
    const early = runMockSim({ member_overrides: { '1': { retirement_age: 45 } } })
    const late = runMockSim({ member_overrides: { '1': { retirement_age: 70 } } })
    expect(late.success_probability).toBeGreaterThan(early.success_probability)
  })

  it('spending less beats spending more', () => {
    const lean = runMockSim({ spending_delta_pct: -20 })
    const rich = runMockSim({ spending_delta_pct: 20 })
    expect(lean.ending_net_worth.p50).toBeGreaterThan(rich.ending_net_worth.p50)
  })

  it('claiming Social Security later beats claiming at 62', () => {
    const at62 = runMockSim({ member_overrides: { '1': { ss_claim_age: 62 } } })
    const at70 = runMockSim({ member_overrides: { '1': { ss_claim_age: 70 } } })
    expect(at70.ending_net_worth.p50).toBeGreaterThan(at62.ending_net_worth.p50)
  })
})

describe('single-axis interpolation (smooth slider response)', () => {
  const ret = (age: number, id = '1'): ScenarioParams => ({
    member_overrides: { [id]: { retirement_age: age } },
  })

  it('blends between the two bracketing lattice points', () => {
    // 63 sits between the 62 lattice point and the 65 baseline anchor.
    const lo = runMockSim(ret(62)).ending_net_worth.p50
    const hi = runMockSim(ret(65)).ending_net_worth.p50 // == baseline (65 is Brian's default)
    const mid = runMockSim(ret(63)).ending_net_worth.p50
    const [min, max] = lo < hi ? [lo, hi] : [hi, lo]
    expect(mid).toBeGreaterThan(min)
    expect(mid).toBeLessThan(max)
    expectShape(runMockSim(ret(63)))
  })

  it('keeps the age axis and produces a fresh (non-aliased) result', () => {
    const interp = runMockSim(ret(63))
    expect(interp.ages).toEqual(baseline().ages)
    // not the same object reference as either stored endpoint
    const p62 = fixtures.axes
      .find((a) => a.id === 'retirement_age:1')!
      .points.find((p) => p.value === 62)!.result
    expect(interp).not.toBe(p62)
  })

  it('takes milestones from a real engine point (integer ages)', () => {
    const interp = runMockSim(ret(64))
    expect(interp.milestones.length).toBeGreaterThan(0)
    for (const m of interp.milestones) expect(Number.isInteger(m.age)).toBe(true)
  })

  it('clamps beyond the lattice range to the nearest endpoint', () => {
    const clamped = runMockSim(ret(30)) // below the min lattice value (45)
    const at45 = runMockSim(ret(45))
    expect(clamped).toEqual(at45)
  })
})

describe('fallbacks', () => {
  it('multi-slider drafts resolve to a valid nearest golden', () => {
    const r = runMockSim({
      member_overrides: { '1': { retirement_age: 58 }, '2': { retirement_age: 58 } },
      spending_delta_pct: -15,
    })
    expectShape(r)
  })

  it('a params set with a custom event resolves to a valid nearest golden', () => {
    const r = runMockSim({
      monthly_savings_delta: -500,
      events: [{ name: 'Sabbatical', kind: 'recurring_expense', amount_monthly: 2000, start_age: 50, end_age: 51 }],
    })
    expectShape(r)
  })
})
