/** Mock /simulate (v2, #8): replays REAL-engine golden fixtures instead of
 * reimplementing Monte-Carlo dynamics. The old seeded GBM shadow engine drifted
 * from `gol.sim` forever (three T-006 contract flags were mock-vs-backend
 * drift); it is gone.
 *
 * Fixtures (`fixtures/sim-fixtures.json`) are generated by
 * `server/scripts/gen_mock_fixtures.py`: the db.ts demo household run through the
 * pinned engine across a lattice over the studio's interactive sliders. A
 * request is served by:
 *   1. exact canonical-param match (named scenarios + every lattice point), else
 *   2. linear interpolation between the two bracketing lattice points when a
 *      single slider moved off baseline (bands blended; milestones from the
 *      nearer point), else
 *   3. the nearest stored point verbatim (multi-slider drafts, events, etc.).
 * So charts still respond smoothly to a single slider drag, without a second
 * engine to keep in sync.
 */

import type { ScenarioParams, SimResult } from '../types'
import { cleanParams, effectiveMemberTiming, serializeParams } from '@/lib/scenarioParams'
import fixturesJson from './fixtures/sim-fixtures.json'

type AxisParam =
  | 'retirement_age'
  | 'ss_claim_age'
  | 'spending_delta_pct'
  | 'monthly_savings_delta'
  | 'annual_retirement_spending'

interface FixtureEntry {
  params: ScenarioParams
  result: SimResult
}
interface AxisPoint extends FixtureEntry {
  value: number
}
interface FixtureAxis {
  id: string
  param: AxisParam
  member_id: number | null
  baseline_value: number
  scale: number
  points: AxisPoint[]
}
export interface SimFixtures {
  engine_version: string
  engine_notes: string[]
  reference_year: number
  seed: number
  n_paths: number
  baseline: FixtureEntry
  scenarios: { name: string; params: ScenarioParams; result: SimResult }[]
  axes: FixtureAxis[]
}

export const fixtures = fixturesJson as unknown as SimFixtures

/* --------------------------- lookup indexes ------------------------------- */

/** Every stored point, keyed by its canonical param serialization. */
const exactByKey = new Map<string, SimResult>()
/** Per-axis points (baseline value injected), sorted ascending for bracketing. */
const axisSorted = new Map<string, { value: number; result: SimResult }[]>()
/** Flat list of every stored point for the nearest-neighbor fallback. */
const allEntries: FixtureEntry[] = [{ params: {}, result: fixtures.baseline.result }]

exactByKey.set(serializeParams({}), fixtures.baseline.result)
for (const s of fixtures.scenarios) {
  exactByKey.set(serializeParams(s.params), s.result)
  allEntries.push({ params: s.params, result: s.result })
}
for (const ax of fixtures.axes) {
  const pts: { value: number; result: SimResult }[] = [
    { value: ax.baseline_value, result: fixtures.baseline.result },
  ]
  for (const p of ax.points) {
    exactByKey.set(serializeParams(p.params), p.result)
    allEntries.push({ params: p.params, result: p.result })
    pts.push({ value: p.value, result: p.result })
  }
  pts.sort((a, b) => a.value - b.value)
  axisSorted.set(ax.id, pts)
}

/* --------------------------- param extraction ----------------------------- */

/** The effective slider value an axis carries for these params (baseline when
 * the slider is untouched). Mirrors the studio's own param resolution. */
function axisValue(ax: FixtureAxis, params: ScenarioParams): number {
  switch (ax.param) {
    case 'retirement_age':
      return (
        effectiveMemberTiming(params, ax.member_id!, 'retirement_age', ax.baseline_value, ax.member_id === 1) ??
        ax.baseline_value
      )
    case 'ss_claim_age':
      return (
        effectiveMemberTiming(params, ax.member_id!, 'ss_claim_age', ax.baseline_value, false) ??
        ax.baseline_value
      )
    case 'spending_delta_pct':
      return params.spending_delta_pct ?? 0
    case 'monthly_savings_delta':
      return params.monthly_savings_delta ?? 0
    case 'annual_retirement_spending':
      return params.annual_retirement_spending ?? ax.baseline_value
  }
}

/** Params the lattice can't represent on a single axis — fall straight to the
 * nearest stored point. */
function isComplex(p: ScenarioParams): boolean {
  return (p.events?.length ?? 0) > 0 || p.return_override_pct != null || p.inflation_override_pct != null
}

/* ---------------------------- interpolation ------------------------------- */

const round2 = (x: number) => Math.round(x * 100) / 100
const lerp = (a: number, b: number, t: number) => a + (b - a) * t
const lerpArr = (a: number[], b: number[], t: number) => a.map((v, i) => round2(lerp(v, b[i]!, t)))

function lerpRuin(a: number | null, b: number | null, t: number): number | null {
  if (a == null || b == null) return t < 0.5 ? a : b
  return Math.round(lerp(a, b, t) * 10) / 10
}

/** Linear blend of two lattice results. Bands/deterministic series blend
 * element-wise; milestones and assumptions come from the nearer point. */
function blend(a: SimResult, b: SimResult, t: number): SimResult {
  const near = t < 0.5 ? a : b
  const d = a.deterministic
  const db = b.deterministic
  const p = a.percentiles
  const pb = b.percentiles
  return {
    engine_version: a.engine_version,
    engine_notes: a.engine_notes,
    assumptions: near.assumptions,
    n_paths: a.n_paths,
    seed: a.seed,
    start_year: a.start_year,
    ages: a.ages,
    deterministic: {
      net_worth: lerpArr(d.net_worth, db.net_worth, t),
      invested: lerpArr(d.invested, db.invested, t),
      cash: lerpArr(d.cash, db.cash, t),
      property: lerpArr(d.property, db.property, t),
      debt: lerpArr(d.debt, db.debt, t),
    },
    percentiles: {
      p10: lerpArr(p.p10, pb.p10, t),
      p25: lerpArr(p.p25, pb.p25, t),
      p50: lerpArr(p.p50, pb.p50, t),
      p75: lerpArr(p.p75, pb.p75, t),
      p90: lerpArr(p.p90, pb.p90, t),
    },
    success_probability: Math.round(lerp(a.success_probability, b.success_probability, t) * 1000) / 1000,
    median_ruin_age: lerpRuin(a.median_ruin_age, b.median_ruin_age, t),
    ending_net_worth: {
      p10: round2(lerp(a.ending_net_worth.p10, b.ending_net_worth.p10, t)),
      p50: round2(lerp(a.ending_net_worth.p50, b.ending_net_worth.p50, t)),
      p90: round2(lerp(a.ending_net_worth.p90, b.ending_net_worth.p90, t)),
    },
    milestones: near.milestones,
  }
}

function interpolateAxis(ax: FixtureAxis, v: number): SimResult {
  const pts = axisSorted.get(ax.id)!
  if (v <= pts[0]!.value) return pts[0]!.result
  const last = pts[pts.length - 1]!
  if (v >= last.value) return last.result
  let i = 0
  while (i < pts.length - 1 && !(pts[i]!.value <= v && v <= pts[i + 1]!.value)) i++
  const lo = pts[i]!
  const hi = pts[i + 1]!
  if (v === lo.value) return lo.result
  if (v === hi.value) return hi.result
  return blend(lo.result, hi.result, (v - lo.value) / (hi.value - lo.value))
}

/** Closest stored point by normalized distance across all slider axes. */
function nearest(params: ScenarioParams): SimResult {
  let best = fixtures.baseline.result
  let bestDist = Infinity
  for (const entry of allEntries) {
    let dist = 0
    for (const ax of fixtures.axes) {
      const d = (axisValue(ax, params) - axisValue(ax, entry.params)) / ax.scale
      dist += d * d
    }
    if (dist < bestDist) {
      bestDist = dist
      best = entry.result
    }
  }
  return best
}

/* ------------------------------ public API -------------------------------- */

/** Resolve a /simulate request against the golden fixtures. The returned object
 * may alias a fixture (the caller — mockRequest — structuredClones responses),
 * except interpolated results, which are always fresh. */
export function runMockSim(params: ScenarioParams): SimResult {
  const clean = cleanParams(params)
  const exact = exactByKey.get(serializeParams(clean))
  if (exact) return exact
  if (isComplex(clean)) return nearest(clean)

  const changed = fixtures.axes.filter((ax) => axisValue(ax, clean) !== ax.baseline_value)
  if (changed.length === 1) return interpolateAxis(changed[0]!, axisValue(changed[0]!, clean))
  if (changed.length === 0) return fixtures.baseline.result
  return nearest(clean)
}
